title: Made by Ogamdo
description: > # this means to ignore newlines until "baseurl:"
 I am intereted in Game and AI.
permalink: ':title/'
baseurl: "/Ogamdo" # the subpath of your site, e.g. /blog
url: "https://ogamdo.github.io" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Ogamdo # add your name
author-img: OgamdoImg.jpg  # add your photo
about-author: I am a Game developer focusing on client and AI. # add description
social-twitter: # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: https://github.com/Ogamdo?tab=repositories
social-linkedin: # add your Linkedin handle
social-email: BellOfJerusalem@proton.me

# Disqus
discus-identifier: mr-brown # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
